- name: Ansible VS Code Extension by Red Hat
  ansible.builtin.shell: code --install-extension redhat.ansible
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/redhat.ansible-*"


- name: Favorite Ansible Extensions
  ansible.builtin.shell: "code --install-extension {{item}}"
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/{{item}}-*"
  loop:
  - redhat.ansible
  - ms-python.python

- name: Install Ansible Lint
  include_tasks: ansible-lint.yml
