- name: Pkg ansible-lint Debian
  ansible.builtin.apt:
    pkg:
    - ansible-lint
  become: true
  when: ansible_os_family == 'Debian'

- name: Pkg ansible-lint Red Hat
  ansible.builtin.dnf:
    name:
      - ansible-lint
    state: latest
  become: true
  when: ansible_os_family == 'RedHat'
